server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: user-management-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    consumer:
      group-id: group-1
      bootstrap-servers: 127.0.0.1:9092
  datasource:
    url: jdbc:postgresql://postgresqldb_service:5432/user_management_db
    username: postgres
    password: postgres
    hikari:
      maximumPoolSize: 100
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

default:
  time-zone: UTC